### ISSUE TITLE
i2c error

### ISSUE THREAD

**Issue by BigNerd95** [OpenIPC/chaos_calmer#31]
I'm trying to use this [firmware](http://flyrouter.net/downloads/software/ipcam/GitHub_OpenWrt/Firmware/openwrt-hisilicon-armv5tej-3.4.35-initramfs-uImage) on a ip cam with soc hi3518ev200

Looking inside original filesystem i found
`/mnt/mtd/ipc/modules/load3518e -i -sensor ar0130`
So it is using your default sensor ar0130

I set this inside uboot
`setenv bootcmd 'setenv bootargs totalmem=64M mem=40M sensor=ar0130 hieth.mdioifu=0 hieth.mdioifd=0 phyaddru=0 phyaddrd=1 console=ttyAMA0,115200; tftp 0x82000000 openwrt-hisilicon-armv5tej-3.4.35-initramfs-uImage; bootm 0x82000000'`

The camera is booting correctly, i can access the shell via serial and load LUCI in my browser

But during boot i see a lot of these messages
```
[   45.562448] hi_i2c_wait_txfifo_notfull->241: 
[   45.566651] abort! last int_raw_status: 0x750!
[   45.571415] 
[   45.572917] hi_i2c_abortprocess->87: 
[   45.576406] tx_abrt_src is 1.
[   45.579545] 
[   45.581685] hi_i2c_wait_txfifo_notfull->241: 
[   45.585888] abort! last int_raw_status: 0x750!
[   45.590646] 
[   45.592147] hi_i2c_abortprocess->87: 
[   45.595636] tx_abrt_src is 1.
[   45.598775] 
[   45.600926] hi_i2c_wait_txfifo_notfull->241: 
[   45.605131] abort! last int_raw_status: 0x750!
[   45.609752] 
[   45.611393] hi_i2c_abortprocess->87: 
[   45.614888] tx_abrt_src is 1.
[   45.618027] 
[   45.620098] hi_i2c_wait_txfifo_notfull->241: 
[   45.624441] abort! last int_raw_status: 0x750!
[   45.629066] 
[   45.630625] hi_i2c_abortprocess->87: 
[   45.634117] tx_abrt_src is 1.
```

And if i load `http://192.168.1.10:8080/image.jpg` it fails
Do I have to pass additional boot arguments?
For example i had to pass `phyaddru=0 phyaddrd=1` insted of `phyaddru=1 phyaddrd=2` to get network working
Maybe the i2c is mapped on different addresses too?
Where can I investigate?

If i run `hisi-load.sh` it prints some messages but then it hangs
```
root@OpenIPC_HI35xx:/# hisi-load.sh 

=====================

Sensor table:
 9m034
 ar0130 (ok), ar0230, ar0237
 imx222 (ok)
 jxf22, jxh62
 mn34222
 ov2718, ov9712, ov9732, ov9750, ov9752
 sc1045, sc1135, sc1145, sc2035, sc2045, sc2135, sc2235

=====================

Current options:
 - processor: hi3518ev200
 - total memory: 64M
 - linux memory: 40M
 - sensor: ar0130
 - mem_start: 0x80000000
 - mmz_start: 0x82800000
 - mmz_size: 24M

=====================

[  891.295235] unload adec.ko ...OK!
[  891.315789] unload aenc.ko ...OK!
[  891.336334] unload ao.ko ...OK!
[  891.356749] unload ai.ko ...OK!
[  891.374276] unload hi3518e_aio.ko ...OK!
[  891.392432] acodec exited!
Remove audio...
module is not loaded
[  891.426004] unload sensor_i2c.ko ...OK!
[  891.446789] unload pwm.ko ...OK!
[  891.466752] unload ive.ko for Hi3518EV200...OK!
[  891.488065] unload rc.ko ...OK!
[  891.508196] unload jpege.ko ...OK!
[  891.528512] unload h264e.ko ...OK!
[  891.548561] unload chnl.ko for Hi3518EV200...OK!

```
At this point I have to reboot the camera by removing power, because it does not exit even if i press ctrl+C

Thank you very much for this amazing project!

**Comment by DeeKey** [comment]
Is this problem still actual? Both your SOc and videochip are supported and should work.
If this issue is still valid for you could you please clean install the latest build of the FW.
Installation process is described on the [main site](https://openipc.org/firmware/)

**Comment by ZigFisher** [comment]
The information is irrelevant.
See now https://openipc.org/firmware/
