### ISSUE TITLE
DAHUA VTO2211G-WP chip HI3516CRBCV500

### ISSUE THREAD

**Issue by roysbike** [OpenIPC/chaos_calmer#79]
is the chip supported HI3516CRBCV500?  I need VTO update firmware to openipc
![IMG_5739](https://user-images.githubusercontent.com/2388223/124394752-7f975380-dd09-11eb-92da-286073218bec.jpg)
![IMG_5736](https://user-images.githubusercontent.com/2388223/124394762-858d3480-dd09-11eb-8e00-6866c237971c.jpg)

**Comment by widgetii** [comment]
Basic HiSilicon CV500 support was added to OpenIPC 2.1
